2 add src code
UCL-ARC/fortran-tooling pull request #17
Opened 2024-06-04 08:45 UTC by connoraird

I have taken the F77 code provided by @qiUip and converted to F90

NOTE: We still require a specifically formatted input file for this to work, which do not yet have

2024-08-29 09:00 UTC, tkoskela commented on src/poisson.f90
> +            real, intent(out)     :: vb(3,mxc), vb1(mxc), vb2(mxc)
Arrays are statically allocated. We may want to change this to dynamic if we want to do experiments on performance.

2024-08-29 09:01 UTC, tkoskela commented on src/poisson.f90
> +                 num_neumann_boundary_conditions
I would put these into a data structure and pass into subroutines, rather than having them as globals

2024-08-29 09:03 UTC, tkoskela commented on src/poisson.f90
> +                            eta, res, ad
Exercise for documentation auto generation

2024-08-29 09:05 UTC, tkoskela commented on src/poisson.f90
> +                  qa       = 0.3333333*qq*ar
```suggestion
                  qa       = 1.0/3.0*qq*ar
```

2024-08-29 09:18 UTC, tkoskela commented on src/poisson.f90
> +                  end do
Is this a duplicate of L355-L368?

2024-08-29 09:26 UTC, tkoskela commented on src/poisson.f90
> +                  write(file_io,'(i5,8f10.5)') ip,coordinates(1,ip),coordinates(2,ip),z,z,nodal_value_of_f(ip),z,z,z
Why the `z`s?

2024-08-29 09:28 UTC, ilectra reviewed
Break down arguments into several lines in subroutine/function definitions, please!

2024-08-29 09:31 UTC, tkoskela commented on src/poisson.f90
> +            end do
```suggestion
                  boundary_index = 1
                  nodal_value_of_f = 0.0
                  f_increment = 0.0
                  pre_conditioning_matrix = 0.0
                  rhs_vector = 0.0
```

2024-08-30 07:19 UTC, tkoskela commented on src/Makefile
> +	gfortran $(FFLAGS) poisson.o main.o -o poisson
These two lines have got duplicated somehow

```suggestion
	gfortran $(FFLAGS) -c poisson.f90 main.f90
	gfortran $(FFLAGS) poisson.o main.o -o poisson
```

2024-09-06 10:27 UTC, tkoskela commented on CMakeLists.txt
> +
My gfortran is again unhappy about line truncation. This fixes it for gfortran but I'm not sure if this is portable
```suggestion
set(CMAKE_Fortran_FLAGS "-ffree-line-length-none")
```

2024-09-06 10:29 UTC, tkoskela requested changes
Could you also add a README with instructions on how to run the mesh generator and the solver?

2024-09-16 14:55 UTC, connoraird commented
> Could you also add a README with instructions on how to run the mesh generator and the solver?

I have added this now. Is there anything else needed or can we merge?

2024-09-17 10:53 UTC, tkoskela approved these changes
Looks good!

2024-09-30 11:22 UTC, merged